Retail Sales and Customer Analytics

In [3]:
import pandas as pd
import os

In [4]:
os.getcwd()

'c:\\Users\\hp\\Desktop\\Workshop'

In [5]:
df = pd.read_csv("Datasets/retail_sales_project_dataset (1).csv")

In [6]:
df.shape

(2000, 34)

In [7]:
df.head()

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
0,T100000,C466,NaN,45.0,Nairobi,Nairobi,2026-01-10,P544,Jeans,NaN,...,Pickup,2.0,NaN,Damaged,Central,NaN,NaN,2025,NaN,1.0
1,T100001,C350,Female,25.0,Eldoret,Eldoret,2025-11-12,P754,Rice,groceries,...,Pickup,4.0,NaN,NaN,East,NaN,NaN,2025,NaN,5.0
2,T100002,C154,NaN,NaN,Kisumu,Nakuru,2025-09-07,P394,Lamp,Home,...,Delivery,1.0,NaN,Damaged,Central,NaN,NaN,2025,Bad,3.0
3,T100003,C360,male,NaN,Kisumu,Nakuru,2025-03-08,P784,Shoes,Clothing,...,Delivery,2.0,NaN,Wrong Item,West,NaN,NaN,2025,NaN,4.0
4,T100004,C184,FEMALE,45.0,Mombasa,Nairobi,2025-10-13,P280,Mouse,electronics,...,Pickup,4.0,NaN,Changed Mind,Central,NaN,NaN,2025,Bad,2.0

In [8]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Customer_Gender', 'Customer_Age',
       'City', 'Branch', 'Sales_Date', 'Product_ID', 'Product_Name',
       'Category', 'Brand', 'Unit_Price', 'Quantity', 'Discount', 'Tax',
       'Total_Sales', 'Cost', 'Profit', 'Payment_Method', 'Salesperson',
       'Customer_Type', 'Membership', 'Promotion', 'Stock_Level',
       'Delivery_Method', 'Customer_Rating', 'Return_Status', 'Return_Reason',
       'Region', 'Month', 'Quarter', 'Year', 'Feedback', 'Satisfaction'],
      dtype='str')

In [9]:
df.info

<bound method DataFrame.info of      Transaction_ID Customer_ID Customer_Gender  Customer_Age     City  \
0           T100000        C466             NaN          45.0  Nairobi
1           T100001        C350          Female          25.0  Eldoret
2           T100002        C154             NaN           NaN   Kisumu
3           T100003        C360           male            NaN   Kisumu
4           T100004        C184          FEMALE          45.0  Mombasa
...             ...         ...             ...           ...      ...
1995        T101731        C404           male           18.0  Eldoret
1996        T100977        C451          Female          25.0  Eldoret
1997        T100925         C83          FEMALE          34.0   Kisumu
1998        T100968        C278           male            NaN  Mombasa
1999        T101400        C181          Female          60.0  Eldoret

       Branch  Sales_Date Product_ID Product_Name     Category  ...  \
0     Nairobi  2026-01-10       P544        Jeans          NaN  ...
1     Eldoret  2025-11-12       P754         Rice    groceries  ...
2      Nakuru  2025-09-07       P394         Lamp         Home  ...
3      Nakuru  2025-03-08       P784        Shoes     Clothing  ...
4     Nairobi  2025-10-13       P280        Mouse  electronics  ...
...       ...         ...        ...          ...          ...  ...
1995   Kisumu  2025-11-25       P148        Jeans     Clothing  ...
1996   Nakuru  2025-11-15       P505        Jeans          NaN  ...
1997   Kisumu  2025-11-13       P699        Mouse  electronics  ...
1998   Nakuru  2026-06-07       P449       Jacket     Clothing  ...
1999   Nakuru  2025-01-26       P449        Mouse          NaN  ...

     Delivery_Method  Customer_Rating  Return_Status  Return_Reason   Region  \
0             Pickup              2.0            NaN        Damaged  Central
1             Pickup              4.0            NaN            NaN     East
2           Delivery              1.0            NaN        Damaged  Central
3           Delivery              2.0            NaN     Wrong Item     West
4             Pickup              4.0            NaN   Changed Mind  Central
...              ...              ...            ...            ...      ...
1995             NaN              1.0   Not Returned     Wrong Item    North
1996        Delivery              5.0       Returned   Changed Mind     East
1997          Pickup              5.0       Returned        Damaged     West
1998        Delivery              NaN   Not Returned   Changed Mind     West
1999          Pickup              2.0            NaN     Wrong Item    North

      Month  Quarter  Year Feedback Satisfaction
0       NaN      NaN  2025      NaN          1.0
1       NaN      NaN  2025      NaN          5.0
2       NaN      NaN  2025      Bad          3.0
3       NaN      NaN  2025      NaN          4.0
4       NaN      NaN  2025      Bad          2.0
...     ...      ...   ...      ...          ...
1995    NaN      NaN  2025      Bad          4.0
1996    NaN      NaN  2025  Average          4.0
1997    NaN      NaN  2025  Average          3.0
1998    NaN      NaN  2025      NaN          2.0
1999    NaN      NaN  2025      Bad          4.0

[2000 rows x 34 columns]>

In [12]:
df.dtypes

Transaction_ID         str
Customer_ID            str
Customer_Gender        str
Customer_Age       float64
City                   str
Branch                 str
Sales_Date             str
Product_ID             str
Product_Name           str
Category               str
Brand                  str
Unit_Price         float64
Quantity           float64
Discount           float64
Tax                float64
Total_Sales        float64
Cost               float64
Profit             float64
Payment_Method         str
Salesperson            str
Customer_Type          str
Membership             str
Promotion              str
Stock_Level        float64
Delivery_Method        str
Customer_Rating    float64
Return_Status          str
Return_Reason          str
Region                 str
Month              float64
Quarter            float64
Year                 int64
Feedback               str
Satisfaction       float64
dtype: object

In [70]:
print("Customer Gender:")
print(df["Customer_Gender"].unique())

print("\nCategories:")
print(df["Category"].unique())

print("\nPayment Methods:")
print(df["Payment_Method"].unique())

print("\nBranches:")
print(df["Branch"].unique())

print("\nCustomer Types:")
print(df["Customer_Type"].unique())

print("\nMembership:")
print(df["Membership"].unique())

Customer Gender:
<StringArray>
[nan, 'Female', ' Male ', 'Male']
Length: 4, dtype: str

Categories:
<StringArray>
[          nan,   'groceries',        'Home',    'Clothing', 'electronics',
 'Electronics',    'clothing',   'Groceries',        'home']
Length: 9, dtype: str

Payment Methods:
<StringArray>
['Card', 'Cash', nan, 'cash', 'Mobile']
Length: 5, dtype: str

Branches:
<StringArray>
['Nairobi', 'Eldoret', 'Nakuru', 'Mombasa', 'Kisumu']
Length: 5, dtype: str

Customer Types:
<StringArray>
[nan, 'New', 'Returning']
Length: 3, dtype: str

Membership:
<StringArray>
['no', 'Yes', 'YES', 'No']
Length: 4, dtype: str

In [10]:
df.describe

<bound method NDFrame.describe of      Transaction_ID Customer_ID Customer_Gender  Customer_Age     City  \
0           T100000        C466             NaN          45.0  Nairobi
1           T100001        C350          Female          25.0  Eldoret
2           T100002        C154             NaN           NaN   Kisumu
3           T100003        C360           male            NaN   Kisumu
4           T100004        C184          FEMALE          45.0  Mombasa
...             ...         ...             ...           ...      ...
1995        T101731        C404           male           18.0  Eldoret
1996        T100977        C451          Female          25.0  Eldoret
1997        T100925         C83          FEMALE          34.0   Kisumu
1998        T100968        C278           male            NaN  Mombasa
1999        T101400        C181          Female          60.0  Eldoret

       Branch  Sales_Date Product_ID Product_Name     Category  ...  \
0     Nairobi  2026-01-10       P544        Jeans          NaN  ...
1     Eldoret  2025-11-12       P754         Rice    groceries  ...
2      Nakuru  2025-09-07       P394         Lamp         Home  ...
3      Nakuru  2025-03-08       P784        Shoes     Clothing  ...
4     Nairobi  2025-10-13       P280        Mouse  electronics  ...
...       ...         ...        ...          ...          ...  ...
1995   Kisumu  2025-11-25       P148        Jeans     Clothing  ...
1996   Nakuru  2025-11-15       P505        Jeans          NaN  ...
1997   Kisumu  2025-11-13       P699        Mouse  electronics  ...
1998   Nakuru  2026-06-07       P449       Jacket     Clothing  ...
1999   Nakuru  2025-01-26       P449        Mouse          NaN  ...

     Delivery_Method  Customer_Rating  Return_Status  Return_Reason   Region  \
0             Pickup              2.0            NaN        Damaged  Central
1             Pickup              4.0            NaN            NaN     East
2           Delivery              1.0            NaN        Damaged  Central
3           Delivery              2.0            NaN     Wrong Item     West
4             Pickup              4.0            NaN   Changed Mind  Central
...              ...              ...            ...            ...      ...
1995             NaN              1.0   Not Returned     Wrong Item    North
1996        Delivery              5.0       Returned   Changed Mind     East
1997          Pickup              5.0       Returned        Damaged     West
1998        Delivery              NaN   Not Returned   Changed Mind     West
1999          Pickup              2.0            NaN     Wrong Item    North

      Month  Quarter  Year Feedback Satisfaction
0       NaN      NaN  2025      NaN          1.0
1       NaN      NaN  2025      NaN          5.0
2       NaN      NaN  2025      Bad          3.0
3       NaN      NaN  2025      NaN          4.0
4       NaN      NaN  2025      Bad          2.0
...     ...      ...   ...      ...          ...
1995    NaN      NaN  2025      Bad          4.0
1996    NaN      NaN  2025  Average          4.0
1997    NaN      NaN  2025  Average          3.0
1998    NaN      NaN  2025      NaN          2.0
1999    NaN      NaN  2025      Bad          4.0

[2000 rows x 34 columns]>

In [28]:
df[["Unit_Price", "Quantity", "Discount", "Tax",
    "Total_Sales", "Cost", "Profit", "Customer_Rating"]].describe()

,Unit_Price,Quantity,Discount,Tax,Total_Sales,Cost,Profit,Customer_Rating
count,1338.000000,1315.000000,1749.000000,2000.000000,863.000000,863.000000,863.000000,1652.000000
mean,125.135747,1.666160,28.227559,21.692015,176.092051,125.083210,51.008841,2.999395
std,166.333435,4.246267,39.382791,86.502649,880.047971,628.014439,276.442277,1.403250
min,-10.000000,-2.000000,0.000000,0.000000,-989.380000,-818.930000,-465.140000,1.000000
25%,-10.000000,-2.000000,5.000000,0.000000,-100.000000,-72.590000,-33.970000,2.000000
50%,8.900000,-2.000000,15.000000,0.000000,-10.000000,-7.200000,-2.540000,3.000000
75%,257.487500,5.000000,20.000000,0.000000,20.000000,17.145000,9.050000,4.000000
max,499.960000,10.000000,110.000000,799.540000,4997.100000,3555.440000,1967.070000,5.000000

In [16]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Customer_Gender     412
Customer_Age        251
City                  0
Branch                0
Sales_Date            0
Product_ID            0
Product_Name          0
Category            483
Brand                 0
Unit_Price          662
Quantity            685
Discount            251
Tax                   0
Total_Sales        1137
Cost               1137
Profit             1137
Payment_Method      420
Salesperson           0
Customer_Type       648
Membership            0
Promotion           660
Stock_Level         685
Delivery_Method     675
Customer_Rating     348
Return_Status       663
Return_Reason       451
Region                0
Month              2000
Quarter            2000
Year                  0
Feedback            504
Satisfaction        335
dtype: int64

In [29]:
df.isnull().sum()[df.isnull().sum()>0]

Customer_Gender     412
Customer_Age        251
Category            483
Unit_Price          662
Quantity            685
Discount            251
Total_Sales        1137
Cost               1137
Profit             1137
Payment_Method      420
Customer_Type       648
Promotion           660
Stock_Level         685
Delivery_Method     675
Customer_Rating     348
Return_Status       663
Return_Reason       451
Month              2000
Quarter            2000
Feedback            504
Satisfaction        335
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df[df.duplicated()]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Customer_Gender, Customer_Age, City, Branch, Sales_Date, Product_ID, Product_Name, Category, Brand, Unit_Price, Quantity, Discount, Tax, Total_Sales, Cost, Profit, Payment_Method, Salesperson, Customer_Type, Membership, Promotion, Stock_Level, Delivery_Method, Customer_Rating, Return_Status, Return_Reason, Region, Month, Quarter, Year, Feedback, Satisfaction]
Index: []

[0 rows x 34 columns]

In [32]:
df["Customer_Age"].describe()

count    1749.000000
mean       47.679245
std        47.529065
min        -5.000000
25%        18.000000
50%        34.000000
75%        60.000000
max       150.000000
Name: Customer_Age, dtype: float64

In [33]:
df[(df["Customer_Age"] < 0) |
    (df["Customer_Age"] > 100)]

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
9,T100009,C479,Female,150.0,Mombasa,Mombasa,2025-04-16,P128,Lamp,Home,...,Pickup,1.0,NaN,Changed Mind,West,NaN,NaN,2025,NaN,5.0
17,T100017,C159,Female,-5.0,Mombasa,Nairobi,2025-02-05,P443,Bread,NaN,...,Pickup,3.0,Returned,Wrong Item,West,NaN,NaN,2025,Good,4.0
18,T100018,C367,NaN,150.0,Kisumu,Nakuru,2025-06-08,P253,Keyboard,Electronics,...,NaN,4.0,NaN,Wrong Item,Central,NaN,NaN,2025,Good,NaN
22,T100022,C373,Female,150.0,Kisumu,Nakuru,2026-04-07,P423,Jeans,Clothing,...,NaN,1.0,NaN,Changed Mind,East,NaN,NaN,2025,Bad,1.0
30,T100030,C341,FEMALE,-5.0,Kisumu,Nakuru,2026-04-24,P273,Shirt,Clothing,...,NaN,2.0,Not Returned,Changed Mind,East,NaN,NaN,2025,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1986,T100427,C21,FEMALE,-5.0,Nakuru,Mombasa,2025-06-30,P251,Bread,groceries,...,Delivery,1.0,Not Returned,Wrong Item,north,NaN,NaN,2025,Good,2.0
1990,T100118,C250,NaN,150.0,Eldoret,Mombasa,2025-08-04,P416,Sugar,Groceries,...,Pickup,4.0,Not Returned,Changed Mind,South,NaN,NaN,2025,NaN,1.0
1992,T100537,C175,Male,150.0,Mombasa,Kisumu,2025-05-28,P702,Cooker,NaN,...,Pickup,NaN,Not Returned,Wrong Item,Central,NaN,NaN,2025,Average,4.0
1993,T100914,C354,FEMALE,-5.0,Mombasa,Mombasa,2026-01-30,P676,Lamp,Home,...,NaN,1.0,NaN,Damaged,East,NaN,NaN,2025,Bad,2.0
1994,T100160,C487,NaN,150.0,Kisumu,Kisumu,2025-01-30,P838,Shirt,Clothing,...,Delivery,1.0,Not Returned,Damaged,north,NaN,NaN,2025,Bad,4.0

In [11]:
df.loc[
    (df["Customer_Age"] < 0) | (df["Customer_Age"] > 100),
    "Customer_Age"
] = None

In [12]:
df.loc[
    (df["Customer_Age"] < 0) | (df["Customer_Age"] > 100),
    "Customer_Age"
] = None

In [13]:
df["Customer_Age"].value_counts(dropna=False)

Customer_Age
NaN     780
45.0    261
25.0    259
60.0    238
18.0    232
34.0    230
Name: count, dtype: int64

In [37]:
df["Category"] = df["Category"].str.strip()
df["Branch"] = df["Branch"].str.strip()
df["Payment_Method"] = df["Payment_Method"].str.strip()
df["Membership"] = df["Membership"].str.strip()

In [39]:
df["Category"] = df["Category"].str.strip()
df["Branch"] = df["Branch"].str.strip()
df["Payment_Method"] = df["Payment_Method"].str.strip()
df["Membership"] = df["Membership"].str.strip()

In [40]:
print(df["Category"].value_counts())
print(df["Branch"].value_counts())
print(df["Payment_Method"].value_counts())
print(df["Membership"].value_counts())

Category
Electronics    257
Groceries      253
Clothing       243
Home           242
clothing       137
home           133
groceries      127
electronics    125
Name: count, dtype: int64
Branch
Mombasa    408
Nakuru     405
Kisumu     401
Nairobi    397
Eldoret    389
Name: count, dtype: int64
Payment_Method
Cash      435
Mobile    385
Card      381
cash      379
Name: count, dtype: int64
Membership
no     513
Yes    510
No     504
YES    473
Name: count, dtype: int64

In [45]:
df["Customer_Gender"].unique()

<StringArray>
[nan, 'Female', ' male ', 'FEMALE', 'Male']
Length: 5, dtype: str

In [48]:
df["Customer_Gender"] = df["Customer_Gender"].str.title()

In [73]:
df["Sales_Date"] = pd.to_datetime(df["Sales_Date"], errors="coerce")
df["Customer_Age"] = pd.to_numeric(df["Customer_Age"], errors="coerce")

In [53]:
df["Sales_Date"] = pd.to_datetime(df["Sales_Date"], errors="coerce")

In [54]:
df[df["Quantity"] < 0]

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
3,T100003,C360,Male,NaN,Kisumu,Nakuru,2025-03-08,P784,Shoes,Clothing,...,Delivery,2.0,NaN,Wrong Item,West,NaN,NaN,2025,NaN,4.0
4,T100004,C184,Female,45.0,Mombasa,Nairobi,2025-10-13,P280,Mouse,electronics,...,Pickup,4.0,NaN,Changed Mind,Central,NaN,NaN,2025,Bad,2.0
5,T100005,C35,Female,NaN,Mombasa,Nairobi,2026-02-15,P448,Monitor,Electronics,...,Pickup,2.0,NaN,NaN,South,NaN,NaN,2025,Bad,3.0
11,T100011,C142,Female,NaN,Eldoret,Mombasa,2026-06-09,P815,Chair,Home,...,Delivery,3.0,Returned,Wrong Item,West,NaN,NaN,2025,Good,2.0
14,T100014,C439,Female,25.0,Kisumu,Nairobi,2025-09-24,P564,Shirt,Clothing,...,Pickup,1.0,Returned,Changed Mind,North,NaN,NaN,2025,Average,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,T100118,C250,NaN,NaN,Eldoret,Mombasa,2025-08-04,P416,Sugar,Groceries,...,Pickup,4.0,Not Returned,Changed Mind,South,NaN,NaN,2025,NaN,1.0
1992,T100537,C175,Male,NaN,Mombasa,Kisumu,2025-05-28,P702,Cooker,NaN,...,Pickup,NaN,Not Returned,Wrong Item,Central,NaN,NaN,2025,Average,4.0
1994,T100160,C487,NaN,NaN,Kisumu,Kisumu,2025-01-30,P838,Shirt,Clothing,...,Delivery,1.0,Not Returned,Damaged,north,NaN,NaN,2025,Bad,4.0
1996,T100977,C451,Female,25.0,Eldoret,Nakuru,2025-11-15,P505,Jeans,NaN,...,Delivery,5.0,Returned,Changed Mind,East,NaN,NaN,2025,Average,4.0
1999,T101400,C181,Female,60.0,Eldoret,Nakuru,2025-01-26,P449,Mouse,NaN,...,Pickup,2.0,NaN,Wrong Item,North,NaN,NaN,2025,Bad,4.0

In [ ]:
df[df["Unit_Price"] < 0]

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
5,T100005,C35,Female,NaN,Mombasa,Nairobi,2026-02-15,P448,Monitor,Electronics,...,Pickup,2.0,NaN,NaN,South,NaN,NaN,2025,Bad,3.0
6,T100006,C384,Male,60.0,Nakuru,Mombasa,2025-03-29,P628,Shoes,Clothing,...,Pickup,NaN,Not Returned,Changed Mind,South,NaN,NaN,2025,Bad,2.0
7,T100007,C183,Male,18.0,Kisumu,Nakuru,2025-07-24,P365,Jeans,clothing,...,Pickup,2.0,Not Returned,Wrong Item,East,NaN,NaN,2025,Average,4.0
10,T100010,C398,Female,34.0,Mombasa,Nakuru,2025-07-07,P733,Milk,Groceries,...,Pickup,2.0,Returned,Changed Mind,North,NaN,NaN,2025,Good,5.0
12,T100012,C496,Female,45.0,Nairobi,Nakuru,2025-09-17,P598,Shirt,clothing,...,Delivery,2.0,Not Returned,Changed Mind,North,NaN,NaN,2025,Bad,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991,T100566,C398,Female,45.0,Nairobi,Nakuru,2026-02-10,P113,Chair,home,...,Delivery,3.0,Not Returned,NaN,north,NaN,NaN,2025,NaN,5.0
1992,T100537,C175,Male,NaN,Mombasa,Kisumu,2025-05-28,P702,Cooker,NaN,...,Pickup,NaN,Not Returned,Wrong Item,Central,NaN,NaN,2025,Average,4.0
1994,T100160,C487,NaN,NaN,Kisumu,Kisumu,2025-01-30,P838,Shirt,Clothing,...,Delivery,1.0,Not Returned,Damaged,north,NaN,NaN,2025,Bad,4.0
1998,T100968,C278,Male,NaN,Mombasa,Nakuru,2026-06-07,P449,Jacket,Clothing,...,Delivery,NaN,Not Returned,Changed Mind,West,NaN,NaN,2025,NaN,2.0
1999,T101400,C181,Female,60.0,Eldoret,Nakuru,2025-01-26,P449,Mouse,NaN,...,Pickup,2.0,NaN,Wrong Item,North,NaN,NaN,2025,Bad,4.0

In [14]:

df["Discount"].describe()

count    1749.000000
mean       28.227559
std        39.382791
min         0.000000
25%         5.000000
50%        15.000000
75%        20.000000
max       110.000000
Name: Discount, dtype: float64

In [15]:
df[(df["Discount"] < 0) | 
   (df["Discount"] > 100)]

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
7,T100007,C183,Male,18.0,Kisumu,Nakuru,2025-07-24,P365,Jeans,clothing,...,Pickup,2.0,Not Returned,Wrong Item,East,NaN,NaN,2025,Average,4.0
15,T100015,C412,Male,60.0,Nairobi,Nairobi,2025-07-02,P118,Jacket,clothing,...,Delivery,NaN,Not Returned,NaN,Central,NaN,NaN,2025,Bad,NaN
16,T100016,C178,Male,34.0,Nairobi,Nairobi,2025-05-24,P740,Milk,Groceries,...,NaN,2.0,NaN,Changed Mind,North,NaN,NaN,2025,NaN,2.0
30,T100030,C341,FEMALE,NaN,Kisumu,Nakuru,2026-04-24,P273,Shirt,Clothing,...,NaN,2.0,Not Returned,Changed Mind,East,NaN,NaN,2025,NaN,1.0
33,T100033,C219,Male,25.0,Kisumu,Eldoret,2025-11-30,P186,Mouse,electronics,...,Delivery,4.0,NaN,Wrong Item,north,NaN,NaN,2025,Good,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,T101975,C6,Male,45.0,Kisumu,Kisumu,2025-03-25,P182,Jacket,clothing,...,Pickup,2.0,Returned,NaN,Central,NaN,NaN,2025,Bad,5.0
1977,T101977,C322,male,18.0,Mombasa,Nairobi,2025-09-22,P882,Rice,NaN,...,Pickup,3.0,Not Returned,Damaged,West,NaN,NaN,2025,Good,NaN
1978,T101978,C177,FEMALE,NaN,Eldoret,Nakuru,2025-07-11,P125,Milk,Groceries,...,NaN,1.0,NaN,Wrong Item,North,NaN,NaN,2025,Good,5.0
1990,T100118,C250,NaN,NaN,Eldoret,Mombasa,2025-08-04,P416,Sugar,Groceries,...,Pickup,4.0,Not Returned,Changed Mind,South,NaN,NaN,2025,NaN,1.0
1996,T100977,C451,Female,25.0,Eldoret,Nakuru,2025-11-15,P505,Jeans,NaN,...,Delivery,5.0,Returned,Changed Mind,East,NaN,NaN,2025,Average,4.0

In [16]:
df["Profit"].describe()

count     863.000000
mean       51.008841
std       276.442277
min      -465.140000
25%       -33.970000
50%        -2.540000
75%         9.050000
max      1967.070000
Name: Profit, dtype: float64

In [17]:
df[df["Profit"] < 0]

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
3,T100003,C360,male,NaN,Kisumu,Nakuru,2025-03-08,P784,Shoes,Clothing,...,Delivery,2.0,NaN,Wrong Item,West,NaN,NaN,2025,NaN,4.0
4,T100004,C184,FEMALE,45.0,Mombasa,Nairobi,2025-10-13,P280,Mouse,electronics,...,Pickup,4.0,NaN,Changed Mind,Central,NaN,NaN,2025,Bad,2.0
6,T100006,C384,male,60.0,Nakuru,Mombasa,2025-03-29,P628,Shoes,Clothing,...,Pickup,NaN,Not Returned,Changed Mind,South,NaN,NaN,2025,Bad,2.0
7,T100007,C183,Male,18.0,Kisumu,Nakuru,2025-07-24,P365,Jeans,clothing,...,Pickup,2.0,Not Returned,Wrong Item,East,NaN,NaN,2025,Average,4.0
17,T100017,C159,Female,NaN,Mombasa,Nairobi,2025-02-05,P443,Bread,NaN,...,Pickup,3.0,Returned,Wrong Item,West,NaN,NaN,2025,Good,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,T101976,C335,male,NaN,Kisumu,Nairobi,2025-03-19,P961,Mouse,electronics,...,Delivery,NaN,Returned,Changed Mind,West,NaN,NaN,2025,Average,5.0
1983,T101068,C330,NaN,NaN,Nairobi,Kisumu,2025-07-17,P334,Mouse,NaN,...,NaN,3.0,NaN,Wrong Item,Central,NaN,NaN,2025,Good,2.0
1984,T101106,C159,FEMALE,18.0,Nakuru,Nairobi,2025-02-10,P330,Keyboard,electronics,...,Delivery,5.0,NaN,Wrong Item,West,NaN,NaN,2025,Bad,4.0
1986,T100427,C21,FEMALE,NaN,Nakuru,Mombasa,2025-06-30,P251,Bread,groceries,...,Delivery,1.0,Not Returned,Wrong Item,north,NaN,NaN,2025,Good,2.0
1996,T100977,C451,Female,25.0,Eldoret,Nakuru,2025-11-15,P505,Jeans,NaN,...,Delivery,5.0,Returned,Changed Mind,East,NaN,NaN,2025,Average,4.0

In [18]:
df["Profit"].describe()

count     863.000000
mean       51.008841
std       276.442277
min      -465.140000
25%       -33.970000
50%        -2.540000
75%         9.050000
max      1967.070000
Name: Profit, dtype: float64

In [19]:
df[(df["Profit"] < -100) | 
   (df["Profit"] > 100)]

,Transaction_ID,Customer_ID,Customer_Gender,Customer_Age,City,Branch,Sales_Date,Product_ID,Product_Name,Category,...,Delivery_Method,Customer_Rating,Return_Status,Return_Reason,Region,Month,Quarter,Year,Feedback,Satisfaction
1,T100001,C350,Female,25.0,Eldoret,Eldoret,2025-11-12,P754,Rice,groceries,...,Pickup,4.0,NaN,NaN,East,NaN,NaN,2025,NaN,5.0
4,T100004,C184,FEMALE,45.0,Mombasa,Nairobi,2025-10-13,P280,Mouse,electronics,...,Pickup,4.0,NaN,Changed Mind,Central,NaN,NaN,2025,Bad,2.0
20,T100020,C316,Female,25.0,Eldoret,Mombasa,2025-10-22,P439,Milk,Groceries,...,Delivery,3.0,NaN,Damaged,north,NaN,NaN,2025,Average,NaN
25,T100025,C189,male,45.0,Nairobi,Nakuru,2025-04-04,P492,Shoes,NaN,...,Delivery,3.0,NaN,Changed Mind,South,NaN,NaN,2025,Average,1.0
29,T100029,C320,FEMALE,34.0,Mombasa,Nakuru,2025-10-30,P527,Table,Home,...,Pickup,4.0,Returned,Damaged,South,NaN,NaN,2025,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1976,T101976,C335,male,NaN,Kisumu,Nairobi,2025-03-19,P961,Mouse,electronics,...,Delivery,NaN,Returned,Changed Mind,West,NaN,NaN,2025,Average,5.0
1978,T101978,C177,FEMALE,NaN,Eldoret,Nakuru,2025-07-11,P125,Milk,Groceries,...,NaN,1.0,NaN,Wrong Item,North,NaN,NaN,2025,Good,5.0
1979,T101979,C268,FEMALE,34.0,Nairobi,Nairobi,2025-09-09,P330,Jeans,Clothing,...,Delivery,1.0,Returned,Changed Mind,South,NaN,NaN,2025,Good,3.0
1984,T101106,C159,FEMALE,18.0,Nakuru,Nairobi,2025-02-10,P330,Keyboard,electronics,...,Delivery,5.0,NaN,Wrong Item,West,NaN,NaN,2025,Bad,4.0
1985,T100455,C23,male,45.0,Kisumu,Eldoret,2026-05-11,P869,Lamp,Home,...,Delivery,3.0,Not Returned,Wrong Item,West,NaN,NaN,2025,NaN,2.0

In [20]:
df.loc[(df["Profit"] < -100) | 
       (df["Profit"] > 100), 
       ["Transaction_ID", "Profit"]]

     Transaction_ID  Profit
1           T100001  604.71
4           T100004 -181.58
20          T100020 -115.04
25          T100025  831.45
29          T100029  116.75
...             ...     ...
1976        T101976 -194.67
1978        T101978  715.16
1979        T101979  170.04
1984        T101106 -330.16
1985        T100455  488.52

[297 rows x 2 columns]

In [57]:
df.loc[df["Quantity"]< 0 ,"Quantity"] =None

In [58]:
df.loc[df["Unit_Price"] < 0,"Unit_Price"]=None

In [60]:
df.loc[df["Discount"]>100,"Discount"]=None

In [61]:
df["Total_Sales"].describe()

count     863.000000
mean      176.092051
std       880.047971
min      -989.380000
25%      -100.000000
50%       -10.000000
75%        20.000000
max      4997.100000
Name: Total_Sales, dtype: float64

In [62]:
df["Profit"].describe()

count     863.000000
mean       51.008841
std       276.442277
min      -465.140000
25%       -33.970000
50%        -2.540000
75%         9.050000
max      1967.070000
Name: Profit, dtype: float64

In [63]:
df["Quantity"].describe()

count    647.000000
mean       5.451314
std        2.903029
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max       10.000000
Name: Quantity, dtype: float64

In [64]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Customer_Gender     412
Customer_Age        780
City                  0
Branch                0
Sales_Date           59
Product_ID            0
Product_Name          0
Category            483
Brand                 0
Unit_Price         1321
Quantity           1353
Discount            573
Tax                   0
Total_Sales        1137
Cost               1137
Profit             1137
Payment_Method      420
Salesperson           0
Customer_Type       648
Membership            0
Promotion           660
Stock_Level         685
Delivery_Method     675
Customer_Rating     348
Return_Status       663
Return_Reason       451
Region                0
Month              2000
Quarter            2000
Year                  0
Feedback            504
Satisfaction        335
dtype: int64

In [90]:
Q1 = df[["Total_Sales", "Profit", "Quantity"]].quantile(0.25)
Q3 = df[["Total_Sales", "Profit", "Quantity"]].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

lower_bound, upper_bound

(Total_Sales   -280.0
 Profit         -98.5
 Quantity        -4.5
 dtype: float64,
 Total_Sales    200.00
 Profit          73.58
 Quantity        15.50
 dtype: float64)

In [66]:
df.to_csv("cleaned_retail_sales.csv", index=False)

In [67]:
df.shape

(2000, 34)

In [74]:
branch_sales = df.groupby("Branch")["Total_Sales"].sum().sort_values(ascending=False)

branch_sales

Branch
Eldoret    44258.69
Nakuru     30110.31
Nairobi    28595.52
Mombasa    26328.07
Kisumu     22674.85
Name: Total_Sales, dtype: float64

In [75]:
branch_sales_df = branch_sales.reset_index()
branch_sales_df.columns = ["Branch", "Total_Sales"]

branch_sales_df

    Branch  Total_Sales
0  Eldoret     44258.69
1   Nakuru     30110.31
2  Nairobi     28595.52
3  Mombasa     26328.07
4   Kisumu     22674.85

In [76]:
branch_performance = df.groupby("Branch").agg(
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Total_Profit=("Profit", "sum")
).sort_values("Total_Sales", ascending=False)

branch_performance

         Total_Sales  Average_Sales  Total_Quantity  Total_Profit
Branch
Eldoret     44258.69     250.049096           681.0      12790.23
Nakuru      30110.31     166.355304           711.0       9815.14
Nairobi     28595.52     183.304615           615.0       7418.61
Mombasa     26328.07     140.042926           751.0       7814.38
Kisumu      22674.85     140.837578           769.0       6182.27

In [77]:
df["Sales_Date"] = pd.to_datetime(df["Sales_Date"])

monthly_sales = df.groupby(
    df["Sales_Date"].dt.to_period("M")
)["Total_Sales"].sum()

monthly_sales

Sales_Date
2025-01    10265.73
2025-02     6619.27
2025-03     9499.87
2025-04    15472.87
2025-05     9159.18
2025-06    18693.92
2025-07     3285.04
2025-08     3729.91
2025-09      497.36
2025-10     8921.63
2025-11     8099.51
2025-12     6541.93
2026-01     5092.96
2026-02     3071.13
2026-03     8819.34
2026-04     5982.15
2026-05    12339.66
2026-06    11066.44
Freq: M, Name: Total_Sales, dtype: float64

In [78]:
quarterly_sales = df.groupby(
    df["Sales_Date"].dt.to_period("Q")
)["Total_Sales"].sum()

quarterly_sales

Sales_Date
2025Q1    26384.87
2025Q2    43325.97
2025Q3     7512.31
2025Q4    23563.07
2026Q1    16983.43
2026Q2    29388.25
Freq: Q-DEC, Name: Total_Sales, dtype: float64

In [79]:
product_quantity = df.groupby("Product_Name")["Quantity"].sum().sort_values(ascending=False)

product_quantity

Product_Name
Milk        285.0
Sugar       267.0
Bread       258.0
Table       235.0
Shirt       229.0
Cooker      228.0
Mouse       227.0
Lamp        226.0
Rice        225.0
Shoes       224.0
Jacket      220.0
Keyboard    209.0
Chair       191.0
Jeans       185.0
Laptop      174.0
Monitor     144.0
Name: Quantity, dtype: float64

In [80]:
category_profit = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

category_profit

Category
Groceries      7197.54
groceries      6171.66
Home           5549.01
Clothing       4778.26
clothing       3783.86
electronics    3610.53
home           3158.18
Electronics    3004.92
Name: Profit, dtype: float64

In [81]:
age_gender_sales = df.groupby(
    ["Customer_Age", "Customer_Gender"]
)["Total_Sales"].sum().reset_index()

age_gender_sales

    Customer_Age Customer_Gender  Total_Sales
0           18.0           Male       6418.71
1           18.0          Female       -17.61
2           18.0            Male      3511.02
3           25.0           Male      -2185.93
4           25.0          Female     11013.38
5           25.0            Male      1891.50
6           34.0           Male      -2375.57
7           34.0          Female     16948.76
8           34.0            Male      3107.55
9           45.0           Male      14530.10
10          45.0          Female      4481.79
11          45.0            Male      4610.63
12          60.0           Male       3423.60
13          60.0          Female       639.81
14          60.0            Male      1287.77

In [82]:
payment_sales = df.groupby("Payment_Method")["Total_Sales"].sum().sort_values(ascending=False)

payment_sales

Payment_Method
Cash      40290.28
cash      29806.92
Mobile    23905.99
Card      20860.69
Name: Total_Sales, dtype: float64

In [83]:
branch_rating = df.groupby("Branch")["Customer_Rating"].mean().sort_values(ascending=False)

branch_rating

Branch
Eldoret    3.162500
Nairobi    3.087613
Kisumu     3.039514
Mombasa    2.877976
Nakuru     2.839286
Name: Customer_Rating, dtype: float64

In [84]:
promotion_sales = df.groupby("Promotion")["Total_Sales"].sum().sort_values(ascending=False)

promotion_sales

Promotion
Yes    61202.40
No     44099.97
Name: Total_Sales, dtype: float64

In [85]:
discount_sales = df.groupby("Discount")["Total_Sales"].sum().sort_values(ascending=False)

discount_sales

Discount
10.0    25909.26
0.0     25410.82
20.0    18107.74
15.0    17217.27
5.0      3506.86
Name: Total_Sales, dtype: float64

In [86]:
return_status = df["Return_Status"].value_counts()

return_status

Return_Status
Not Returned    671
Returned        666
Name: count, dtype: int64

In [87]:
return_reasons = df[df["Return_Status"] == "Returned"]["Return_Reason"].value_counts()

return_reasons

Return_Reason
Wrong Item      180
Damaged         176
Changed Mind    162
Name: count, dtype: int64

In [88]:
highest_sales = branch_sales.head(1)
lowest_sales = branch_sales.tail(1)

highest_sales, lowest_sales

(Branch
 Eldoret    44258.69
 Name: Total_Sales, dtype: float64,
 Branch
 Kisumu    22674.85
 Name: Total_Sales, dtype: float64)

In [89]:
salesperson_sales = df.groupby("Salesperson")["Total_Sales"].sum().sort_values(ascending=False)

salesperson_sales

Salesperson
EMP9     12166.77
EMP17    11783.97
EMP15    11660.49
EMP1     10531.18
EMP16    10331.03
EMP26     9779.16
EMP18     9562.32
EMP8      8188.94
EMP22     7216.04
EMP14     6840.53
EMP13     6547.86
EMP11     6446.60
EMP10     5596.65
EMP21     5449.22
EMP25     4415.57
EMP12     4322.67
EMP29     3949.33
EMP3      3047.81
EMP28     2960.34
EMP24     2920.57
EMP7      2530.59
EMP19     2218.68
EMP4      2113.11
EMP30     1602.69
EMP2      1502.54
EMP20     1176.96
EMP5       -14.06
EMP6      -598.04
EMP23     -877.76
EMP27    -1404.32
Name: Total_Sales, dtype: float64